In [1]:
#第5章 pandas入门

import pandas as pd

In [2]:
#Series 一维数组对象，包含一个值序列，并且包含索引
obj = pd.Series([4,7,-5,3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,7,-5,3],index=['b','d','a','c']) #可以自定义索引 

In [7]:
obj2

b    4
d    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['b', 'd', 'a', 'c'], dtype='object')

In [9]:
obj2['a']  #访问数组中的对象 与元组类似

-5

In [10]:
obj2[['c','a','d']]

c    3
a   -5
d    7
dtype: int64

In [11]:
obj2[obj2>0]

b    4
d    7
c    3
dtype: int64

In [12]:
obj2*2 #所有值乘以2

b     8
d    14
a   -10
c     6
dtype: int64

In [14]:
import numpy as np
np.exp(obj2)

b      54.598150
d    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
sdata = {'Ohio':3500,'Texas':7100,'Oregon':16000,'Utah':5000}  #如果已经有数据包含在Python字典中，可以使用字典生成一个Series

In [19]:
obj3 = pd.Series(sdata)

In [20]:
obj3

Ohio       3500
Oregon    16000
Texas      7100
Utah       5000
dtype: int64

In [21]:
states =['California','Ohio','Oregon','Texas']

In [24]:
obj4 = pd.Series(sdata,index=states)

In [25]:
obj4  #NaN 为数据缺失 因为‘Utah’并不在states中  ‘California’不在sdata的键中

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas          7100.0
dtype: float64

In [26]:
pd.isnull(obj4)  #使用isnull和notnull来检查缺失数据

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj3+obj4

California        NaN
Ohio           7000.0
Oregon        32000.0
Texas         14200.0
dtype: float64

In [30]:
obj4.name = 'population'

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas          7100.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj.index = ['Bob','Steve','Jeff','Ryan']   #series的索引可以通过按位置赋值的方式进行改变

In [35]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [42]:
###DataFrame表示矩阵的数据表，包含已排序的列集合。既有行索引也有列索引

data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [43]:
frame = pd.DataFrame(data)

In [44]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [45]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [46]:
pd.DataFrame(data,columns=['year','state','pop'])  #指定排序

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [48]:
#如果传入的列不包含在字典中，将会在结果中出现缺失值
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])

In [49]:
frame2 

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [51]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [52]:
frame2.loc['three']##选取特定行

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [53]:
frame2['debt']=16.5

In [54]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [55]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [56]:
frame2['debt']=val

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [58]:
frame2['eastern']=frame2.state =='Ohio'

In [59]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [60]:
del frame2['eastern']  # del删除列

In [61]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [62]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [63]:
frame3 = pd.DataFrame(pop)

In [64]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [65]:
frame3.T
#翻转

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [66]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [67]:
pdata = {'Ohio':frame3['Ohio'][:-1],"Nevada":frame3['Nevada'][:2]}

In [68]:
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [69]:
frame3.index.name = 'year';frame3.columns.name = 'state'

In [70]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [71]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [72]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [73]:
#索引对象
#pandas中的索引对象是用于存储周表情和其他元数据的

obj = pd.Series(range(3),index=['a','b','c'])

In [74]:
index = obj.index

In [75]:
index

Index(['a', 'b', 'c'], dtype='object')

In [76]:
index[1:]

Index(['b', 'c'], dtype='object')

In [77]:
index[1] = 'd'#索引对象是不可变的

TypeError: Index does not support mutable operations

In [78]:
labels = pd.Index(np.arange(3))

In [79]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [80]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [81]:
obj2.index is labels

True

In [82]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [83]:
#索引对象可以包含重复标签
dup_labels=pd.Index(['foo','foo','bar','bar'])

In [84]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [85]:
#重建索引  reindex
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','c','a'])

In [86]:
obj

d    4.5
b    7.2
c   -5.3
a    3.6
dtype: float64

In [87]:
 obj2 = obj.reindex(['a','b','c','d','e'])

In [88]:
obj2

a    3.6
b    7.2
c   -5.3
d    4.5
e    NaN
dtype: float64

In [89]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [90]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [91]:
# ffill 在重建索引时插值 将前一个值复制到后一个中
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [92]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [93]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [94]:
frame2 = frame.reindex(['a','b','c','d'])

In [95]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [96]:
#columns关键字重建索引
states = ['Texas','Utah','California']

In [97]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [98]:
frame.loc[['a','b','c','d'],states]

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [99]:
#轴向上删除条目

obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [100]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [101]:
new_obj = obj.drop('c')

In [102]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [104]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [105]:
#索引值可以从轴向上删除

data=pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New Yprk'],columns=['one','two','three','four'])

In [106]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New Yprk   12   13     14    15

In [107]:
#调用drop时使用标签序列会根据行标签删除值（轴0）
data.drop(['Colorado','Ohio'])  # 删除了Ohio和Colorado 两行

one  two  three  four
Utah        8    9     10    11
New Yprk   12   13     14    15

In [108]:
# 传递axis=1或 axis=‘columns’来从列中删除值
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New Yprk   12     14    15

In [109]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New Yprk   12     14

In [110]:
# 索引、选择与过滤
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])

In [111]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [112]:
obj['b']

1.0

In [113]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [114]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [115]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [116]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [117]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [118]:
obj['b':'c']=5

In [119]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [120]:
 data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [121]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [123]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [124]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [125]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [126]:
data[data<5]=0

In [127]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [129]:
data.iloc[2,[3,0,-1]]

four    11
one      8
four    11
Name: Utah, dtype: int32

In [130]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [131]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [132]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [133]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [134]:
ser = pd.Series(np.arange(3.))

In [137]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [139]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [140]:
ser2[-1]

2.0

In [141]:
ser[:1]

0    0.0
dtype: float64

In [142]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [143]:
ser.iloc[:1]

0    0.0
dtype: float64

In [144]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [145]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [146]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [147]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [148]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [149]:
arr = np.arange(12.).reshape((3,4))

In [150]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [151]:
arr[0]

array([0., 1., 2., 3.])

In [152]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [3]:
import pandas as pd
import numpy as np

In [5]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bed'),index=['Utah','Ohio','Texas','Oregon'])

In [6]:
frame

b         e         d
Utah   -0.148773  0.351186  1.047306
Ohio    0.615440 -0.227285  1.171816
Texas   0.013799  0.521387 -2.146472
Oregon -0.750762  1.674065 -0.720203

In [7]:
f = lambda x: x.max() -x.min()

In [8]:
frame.apply(f)

b    1.366201
e    1.901350
d    3.318288
dtype: float64

In [9]:
frame.apply(f,axis='columns')

Utah      1.196079
Ohio      1.399101
Texas     2.667859
Oregon    2.424827
dtype: float64

In [10]:
format = lambda x: '%.2f'%x

In [11]:
frame.applymap(format)

b      e      d
Utah    -0.15   0.35   1.05
Ohio     0.62  -0.23   1.17
Texas    0.01   0.52  -2.15
Oregon  -0.75   1.67  -0.72

In [12]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [13]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [14]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [15]:
frame.sort_index()  #

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [16]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [17]:
frame.sort_index(axis=1,ascending=False)  #降序排序

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [18]:
#根据值排序 sort_values
obj=pd.Series([4,7,-3,2])

In [19]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [21]:
#默认情况下 缺失值会被排到最后
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [22]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [23]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [24]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [25]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [26]:
#将值分配给组中最大排名
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [28]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

In [29]:
unique = obj.unique()

In [30]:
unique

array(['c', 'a', 'd', 'b'], dtype=object)

In [31]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [34]:
pd.value_counts(obj.values,sort=False)

d    1
a    3
b    2
c    3
dtype: int64

In [35]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [36]:
mask = obj.isin(['b','c'])

In [37]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [38]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [54]:
df = pd.read_csv('D:\A.csv')


In [55]:
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [56]:
pd.read_table('D:\A.csv',sep=',')  #指定分隔符 ，

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [57]:
pd.read_csv('D:\A.csv',header=None)  #自动分配默认列名 或者指定列名

0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [58]:
pd.read_csv('D:\A.csv',names=['a','b','c','d','message']) 

a   b   c   d  message
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [59]:
names = ['a','b','c','d','message']

In [64]:
pd.read_csv('D:\A.csv',names=names,index_col='message') ###指定‘message’为索引列

a   b   c   d
message               
message  a   b   c   d
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [75]:
pd.read_csv('D:/A.csv',skiprows=[0,2,3])

Empty DataFrame
Columns: [1, 2, 3, 4, hello]
Index: []

In [76]:
path = 'D:/b.csv'
result = pd.read_csv(path)

In [77]:
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [78]:
pd.isnull(result) #判断空值

something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [81]:
result = pd.read_csv('D:/b.csv',na_values=['NULL'])

In [82]:
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [83]:
sentinels={'message':['foo','NA'],'something':['two']}

In [84]:
result = pd.read_csv('D:/b.csv',na_values=sentinels)

In [85]:
result

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [90]:
pd.options.display.max_rows = 2  #设置显示 

In [91]:
result = pd.read_csv('D:/b.csv')

In [92]:
result

something  a   b     c   d message
0        one  1   2   3.0   4     NaN
..       ... ..  ..   ...  ..     ...
2      three  9  10  11.0  12     foo

[3 rows x 6 columns]

In [94]:
pd.read_csv('D:/b.csv',nrows=2)  #nrows 指明读取一小部分

something  a  b    c  d message
0       one  1  2  3.0  4     NaN
1       two  5  6  NaN  8   world

In [95]:
###写入csv文件

data = pd.read_csv('D:/A.csv')

In [96]:
data

a   b   c   d message
0   1   2   3   4   hello
.. ..  ..  ..  ..     ...
2   9  10  11  12     foo

[3 rows x 5 columns]

In [99]:
pd.options.display.max_rows = 20 

In [100]:
data

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [101]:
data.to_csv('D:/c.csv')

In [102]:
pd.read_csv('D:/c.csv')

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [103]:
import sys

In [104]:
data.to_csv(sys.stdout,sep='|') # 写入时用  | 分隔 

|a|b|c|d|message
0|1|2|3|4|hello
1|5|6|7|8|world
2|9|10|11|12|foo


In [105]:
data.to_csv(sys.stdout,na_rep='NULL') #  emmm这里因为A.csv是没有空缺值的 

,a,b,c,d,message
0,1,2,3,4,hello
1,5,6,7,8,world
2,9,10,11,12,foo


In [106]:
###JSON数据

obj = """
{"name": "Wes",
"places_lived": ["United States", "Spain", "Germany"],
"pet": null,
"siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
{"name": "Katie", "age": 38,
"pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

import json
result = json.loads(obj)
result


{'name': 'Wes',
 'pet': None,
 'places_lived': ['United States', 'Spain', 'Germany'],
 'siblings': [{'age': 30, 'name': 'Scott', 'pets': ['Zeus', 'Zuko']},
  {'age': 38, 'name': 'Katie', 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [107]:
asjson = json.dumps(result)  #json.dumps可以将py对象转换回JSON

In [108]:
siblings = pd.DataFrame(result['siblings'],columns=['name','age'])  #选出数据

In [109]:
siblings

name  age
0  Scott   30
1  Katie   38