In [1]:
import pandas as pd 
import numpy as np

In [3]:
string_data =pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()# 判空

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0]=None  #创建None值在数组中也被当做NA处理

In [7]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [8]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [9]:
#过滤缺失值
from numpy import nan as NA

In [10]:
data = pd.Series([1,NA,3.5,NA,7])

In [11]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [12]:
data.dropna()  #返回所以非空值和索引

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [15]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
cleaned = data.dropna()  #处理DataFrom对象时dropna（）默认会删除包含缺失值的行

In [18]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [19]:
data.dropna(how='all')  #传入how=‘all’时，将删除所有值均为NA的行

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data[4]=NA  

In [21]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [22]:
data.dropna(axis=1,how='all')  #同样的方式删除列， 传入axis=1

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df = pd.DataFrame(np.random.randn(7,3))

In [24]:
df.iloc[:4,1]=NA

In [25]:
df.iloc[:2,2] =NA

In [26]:
df

0         1         2
0  1.262969       NaN       NaN
1  0.145626       NaN       NaN
2  0.176343       NaN  1.272417
3 -0.646337       NaN -1.094981
4 -1.472426  0.395735 -1.063823
5  0.664979 -0.267496  1.222475
6  0.765543  0.352034  0.279488

In [27]:
df.dropna()

0         1         2
4 -1.472426  0.395735 -1.063823
5  0.664979 -0.267496  1.222475
6  0.765543  0.352034  0.279488

In [28]:
df.dropna(thresh=2)

0         1         2
2  0.176343       NaN  1.272417
3 -0.646337       NaN -1.094981
4 -1.472426  0.395735 -1.063823
5  0.664979 -0.267496  1.222475
6  0.765543  0.352034  0.279488

In [32]:
#fillna()补全缺失值，调用时使用一个常数来替代缺失值 
df.fillna(0)

0         1         2
0  1.262969  0.000000  0.000000
1  0.145626  0.000000  0.000000
2  0.176343  0.000000  1.272417
3 -0.646337  0.000000 -1.094981
4 -1.472426  0.395735 -1.063823
5  0.664979 -0.267496  1.222475
6  0.765543  0.352034  0.279488

In [33]:
#调用fillna时使用字典，可以为不同列设置不同的填充值
df.fillna({1:0.5,2:0})

0         1         2
0  1.262969  0.500000  0.000000
1  0.145626  0.500000  0.000000
2  0.176343  0.500000  1.272417
3 -0.646337  0.500000 -1.094981
4 -1.472426  0.395735 -1.063823
5  0.664979 -0.267496  1.222475
6  0.765543  0.352034  0.279488

In [34]:
_ = df.fillna(0,inplace=True)

In [35]:
df

0         1         2
0  1.262969  0.000000  0.000000
1  0.145626  0.000000  0.000000
2  0.176343  0.000000  1.272417
3 -0.646337  0.000000 -1.094981
4 -1.472426  0.395735 -1.063823
5  0.664979 -0.267496  1.222475
6  0.765543  0.352034  0.279488

In [37]:
#删除重复值
data = pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,3,4,4]})

In [38]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [41]:
#DataFrame的duplicated方法返回的是一个布尔值Series，这个series反映的是每一行是否存在重复
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [42]:
#drop_duplicates()返回的是DataFrame，内容是duplicated返回数组中为False的部分
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [43]:
#假设有个一额外的列，并想基于‘k1’列去除重复值
data['v1']=range(7)

In [44]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
#duplicated和drop_duplicates默认都是保留第一个观测到的值。传入参数keep=‘last’将会返回最后一个
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [46]:
#使用函数或映射进行数据转换
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],
                     'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [47]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [48]:
meat_to_animal = {'bacon':'pig','pulled pork':'pig','pastrami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'salmon'}

In [49]:
#str.lower方法将每个值都转换成小写
lowercased = data['food'].str.lower()

In [50]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [51]:
data['animal'] = lowercased.map(meat_to_animal)

In [52]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [54]:
#使用map是一种可以快捷执行元素转换及其他清洗相关操作的方法
data['food'].map(lambda x: meat_to_animal[x.lower()])


0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [55]:
#替代值

#使用fillna填充缺失值是通用值替换的特殊案例。map可以用来修改一个对象中的子集的值，但是replace提供了更为简单灵活的实现。让我们考虑下面的Series

data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])


In [56]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
#-999可能是缺失值的标识 。 如果使用NA来替代这些值，可以使用repalce方法生成新的Series
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [58]:
data.replace([-999,-1000],np.nan) #想要一次替代多个值 可以传入一个列表和替代值

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [59]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
#  data.replace()和data.str.replace（）方法是不同的，data.str.replace是对字符串进行按元素替代的。

In [60]:
#重命名轴索引
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])

In [61]:
transform = lambda x : x[:4].upper()

In [62]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [63]:
data.index = data.index.map(transform)

In [64]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [65]:
#rename 想要创建数据集转换后的版本，且不修改原有的数据集  且可以结合字典型对象使用，为标签提供新的值
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [66]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [67]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [68]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [69]:
##离散化和分箱
#连续值经常需要离散化，或者分离成“箱子”进行分析。假设有某项研究中一组人群的数据，你想将他们进行分组，放入离散的年龄框中：

ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [71]:
#将这些年龄分为18-25  26-35  36-60以及61及以上 可以使用pandas中的cut来实现
bins = [19,25,35,60,100]
cats = pd.cut(ages,bins)

In [72]:
cats

[(19, 25], (19, 25], (19, 25], (25, 35], (19, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(19, 25] < (25, 35] < (35, 60] < (60, 100]]

In [73]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [74]:
cats.categories

IntervalIndex([(19, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [75]:
pd.value_counts(cats) #对pandas.cut的结果中的箱数量的计数

(19, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [76]:
pd.cut(ages,[18,26,36,61,100],right=False) #right=False 改变区间的开闭


[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [77]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [78]:
pd.cut(ages,bins,labels=group_names)  #labels选项传递一个列表或数组来传入自定义的箱名

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [79]:
data = np.random.rand(20)

In [80]:
pd.cut(data,4,precision=2)

[(0.16, 0.37], (0.78, 0.98], (0.37, 0.57], (0.78, 0.98], (0.57, 0.78], ..., (0.57, 0.78], (0.16, 0.37], (0.78, 0.98], (0.16, 0.37], (0.57, 0.78]]
Length: 20
Categories (4, interval[float64]): [(0.16, 0.37] < (0.37, 0.57] < (0.57, 0.78] < (0.78, 0.98]]

In [81]:
#qcut是一个与分箱密切先关的函数，它基于样本分位数进行分箱。取决于数据的分布，使用cut通话不会使每个箱具有相同数据量的数据点。
#由于qcut使用样本的分位数，所以可以通过qcut获得等长的箱
data = np.random.randn(1000) #正态分布
cats = pd.qcut(data,4)  #切成四份


In [82]:
cats

[(0.665, 3.252], (0.665, 3.252], (0.665, 3.252], (-0.0295, 0.665], (-0.0295, 0.665], ..., (-0.0295, 0.665], (-0.0295, 0.665], (-3.5309999999999997, -0.743], (-0.743, -0.0295], (-3.5309999999999997, -0.743]]
Length: 1000
Categories (4, interval[float64]): [(-3.5309999999999997, -0.743] < (-0.743, -0.0295] < (-0.0295, 0.665] < (0.665, 3.252]]

In [83]:
pd.value_counts(cats)

(0.665, 3.252]                   250
(-0.0295, 0.665]                 250
(-0.743, -0.0295]                250
(-3.5309999999999997, -0.743]    250
dtype: int64

In [84]:
##检测和过滤异常值

data = pd.DataFrame(np.random.randn(1000,4))

In [85]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.029885    -0.065481    -0.058259    -0.008849
std       1.005363     0.987836     1.041411     0.987175
min      -3.182341    -3.230659    -3.424063    -3.094956
25%      -0.687199    -0.750219    -0.785768    -0.661232
50%      -0.010717    -0.067658    -0.060345    -0.035660
75%       0.605270     0.630652     0.647105     0.631355
max       3.039989     3.259369     2.915145     3.191897

In [86]:
#假设想要找出一列中绝对值大于3的值
col = data[2]

In [87]:
col[np.abs(col)>3]

664   -3.424063
Name: 2, dtype: float64

In [88]:
#要选出所有大于3或小于-3的行，可以对布尔值DataFrame使用any方法
data[(np.abs(data)>3).any(1)]

0         1         2         3
2   -3.144644 -0.525429  2.164834 -0.476704
72  -3.026459 -0.445215  0.235268  3.054984
75  -2.954193 -0.565727 -0.679143  3.191897
138  1.068146 -0.600510  0.791756 -3.094956
157  1.787885  3.259369  0.500055 -1.615834
648 -3.182341  1.317769 -1.076949  1.066656
664  0.536431 -1.804156 -3.424063  1.825866
877  0.783563 -3.230659  0.109899 -0.786698
891  3.039989  0.350731  0.666420  2.302095

In [89]:
#值可以根据这些标准来设置，下面代码限制了-3到3之间的数值
data[np.abs(data)>3] = np.sign(data)*3   

In [90]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.029571    -0.065510    -0.057834    -0.009001
std       1.004168     0.986282     1.040124     0.986108
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.687199    -0.750219    -0.785768    -0.661232
50%      -0.010717    -0.067658    -0.060345    -0.035660
75%       0.605270     0.630652     0.647105     0.631355
max       3.000000     3.000000     2.915145     3.000000

In [92]:
#np.sign(data)根据数据中的值的正负分别生成1和-1的数值
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1 -1.0  1.0 -1.0 -1.0
2 -1.0 -1.0  1.0 -1.0
3 -1.0  1.0  1.0 -1.0
4 -1.0  1.0 -1.0 -1.0

In [93]:
##置换和随机抽样
#使用numpy.random.permutation对DataFrame中的Series或行进行置换（随机重排序）
#在调用permutation时根据想要的轴的长度可以产生一个表示新顺序的整数数组

df = pd.DataFrame(np.arange(5*4).reshape(5,4))

sampler = np.random.permutation(5)

In [94]:
sampler

array([3, 1, 2, 4, 0])

In [95]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [96]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
4  16  17  18  19
0   0   1   2   3

In [97]:
#要选出一个不含有替代值的随机子集，可以使用Series和DataFrame的sample方法

df.sample(n=3)

0  1   2   3
0  0  1   2   3
2  8  9  10  11
1  4  5   6   7

In [98]:
#生成一个带有替代值的样本（允许又重复选择），将replace=True传入sample方法

choices = pd.Series([5,7,-1,6,4])
draws = choices.sample(n=10,replace=True)

In [99]:
draws

1    7
0    5
4    4
1    7
1    7
0    5
2   -1
4    4
2   -1
2   -1
dtype: int64

In [100]:
#字符串对象方法
val = 'a,b,  guido'

In [101]:
val.split(',')  #字符分隔

['a', 'b', '  guido']

In [102]:
#solit经常和strip一起使用，用于清除空格包括换行
pieces = [x.strip() for x in val.split(',')]

In [103]:
pieces

['a', 'b', 'guido']

In [104]:
#这些子字符串可以使用加法与两个冒号分隔符连接在一起
first, second, third = pieces

In [105]:
first + '::'+second + '::' + third

'a::b::guido'

In [106]:
#在字符串‘：：’的join方法中传入一个列表或元组是一种更快的方法
'::'.join(pieces)

'a::b::guido'

In [107]:
#count返回的是某个特定的子字符串在字符串中出现的次数
val.count(',')

2

In [108]:
#replace将用一种模式替代另一种模式。它通常也用于传入空字符串来删除某个模式
val.replace(',','::')

'a::b::  guido'

In [109]:
val.replace(',','')

'ab  guido'

In [110]:
##正则表达式
import re

text = 'foo  bar\t baz  \tqux'

In [111]:
re.split('\s+',text)  #描述一个或多个空白字符的正则表达式是  \s+

['foo', 'bar', 'baz', 'qux']

In [112]:
regex = re.compile('\s+')

In [113]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [114]:
#如果想获得一个所有匹配正则表达式的模式的列表，可以使用findall方法
regex.findall(text)

['  ', '\t ', '  \t']

In [115]:
#pandas 中的向量化字符串函数
data = {'Dave': 'dave@google.com','Steve': 'steve@gmail.com','Rob': 'rob@gmail.com','Wes': np.nan}

In [116]:
data = pd.Series(data)

In [117]:
data

Dave     dave@google.com
Rob        rob@gmail.com
Steve    steve@gmail.com
Wes                  NaN
dtype: object

In [118]:
data.isnull()

Dave     False
Rob      False
Steve    False
Wes       True
dtype: bool

In [119]:
data.str.contains('gmail') #str.contains 检查每行数据是否包含某元素

Dave     False
Rob       True
Steve     True
Wes        NaN
dtype: object

In [124]:
pattern = '([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [125]:
data.str.findall(pattern,flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Rob        [(rob, gmail, com)]
Steve    [(steve, gmail, com)]
Wes                        NaN
dtype: object

In [129]:
#第8章数据规整：连接、联合与重塑
#分层索引

data = pd.Series(np.random.randn(9),index=[['a','a','a','b','b','c','c','d','d'],[1,2,3,1,3,1,2,2,3]])

In [130]:
data

a  1   -0.211934
   2   -0.462639
   3    0.758899
b  1   -0.819544
   3   -0.615695
c  1   -0.080652
   2    0.573844
d  2    0.134235
   3    1.370846
dtype: float64

In [131]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [132]:
data['b']

1   -0.819544
3   -0.615695
dtype: float64

In [133]:
data['b':'c']

b  1   -0.819544
   3   -0.615695
c  1   -0.080652
   2    0.573844
dtype: float64

In [135]:
data.loc[['b','d']]

b  1   -0.819544
   3   -0.615695
d  2    0.134235
   3    1.370846
dtype: float64

In [136]:
data.loc[:,2]

a   -0.462639
c    0.573844
d    0.134235
dtype: float64

In [137]:
data.unstack()

1         2         3
a -0.211934 -0.462639  0.758899
b -0.819544       NaN -0.615695
c -0.080652  0.573844       NaN
d       NaN  0.134235  1.370846

In [139]:
data.unstack().stack()

a  1   -0.211934
   2   -0.462639
   3    0.758899
b  1   -0.819544
   3   -0.615695
c  1   -0.080652
   2    0.573844
d  2    0.134235
   3    1.370846
dtype: float64

In [2]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),index=[['a','a','b','b'],[1,2,1,2]],columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])

In [3]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [4]:
frame.index.names =['key1','key2']

In [5]:
frame.columns.names = ['state','color']

In [6]:
frame


state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [7]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [8]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [9]:
    frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [10]:
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [11]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [12]:
##使用DataFrame的列进行索引
frame = pd.DataFrame({'a':range(7),'b':range(7,0,-1),'c':['one','one','one','two','two','two','two'],'d':[0,1,2,0,1,2,3]})

In [13]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [14]:
##set_index函数会生成一个新的DataFrame，新的DataFrame使用一个或多个列作为索引
frame2 = frame.set_index(['c','d'])

In [15]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [16]:
frame.set_index(['c','d'],drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [17]:
frame2.reset_index()  ##reset_index是set_index的反操作，分层索引的索引层级被移动到列

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [2]:
#数据库风格的DataFrame连接
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})

In [3]:
df2 = pd.DataFrame({'key':['a','b','d'],'data2':range(3)})

In [4]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [5]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [6]:
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [7]:
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [8]:
df3 = pd.DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1':range(7)})

In [9]:
df4 = pd.DataFrame({'rkey':['a','b','d'],'data2':range(3)})

In [10]:
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [11]:
pd.merge(df1,df2,how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [12]:
#根据索引合并
#DataFrame中用于合并的键是他的索引。可以传递left_index=True或right_index=True(或者都传)来表示索引需要用来作为合并的键

left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})

In [13]:
right1 = pd.DataFrame({'group_val':[3.5,7]},index=['a','b'])

In [14]:
left1


key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [15]:
right1

group_val
a        3.5
b        7.0

In [17]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [18]:
#由于默认的合并方法是连接键相交，所以可以使用外连接来进行合并
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [19]:
#使用两边的索引进行合并也是可以的
left2 = pd.DataFrame([[1.,2.],[3.,4.],[5.,6.]],index=['a','c','e'],columns=['Ohio','Nevada'])

In [20]:
right2 = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13,14]],index=['b','c','d','e'],columns=['Missouri','Alabama'])

In [21]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [22]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [23]:
pd.merge(left2,right2,how='outer',left_index=True,right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [24]:
#join方法也可以用于合并多个索引相同或相似但没有重叠列的DataFrame对象
left2.join(right2,how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [26]:
#沿轴向连接
#另一种数据组合操作可互换地称为拼接、绑定或堆叠，NumPy的concatenate函数可以在numpy数组上实现
arr = np.arange(12).reshape((3,4))

In [27]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [29]:
s1 = pd.Series([0,1],index=['a','b'])

In [30]:
s2 = pd.Series([2,3,4],index=['c','d','e'])

In [31]:
s3 = pd.Series([5,6],index=['f','g'])

In [32]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [33]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [34]:
s4 = pd.concat([s1,s3])

In [35]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [37]:
pd.concat([s1,s4],axis=1)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [38]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  1

In [40]:
result = pd.concat([s1,s1,s3],keys=['one','two','three'])

In [41]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [43]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [44]:
#沿着轴向axis=1连接Series的时候，keys则成了DataFrame的列头
pd.concat([s1,s2,s3],axis=1,keys=['one','two','three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [45]:
#联合重叠数据
#假设有两个数据集，这两个数据集的索引全部或部分重叠。 where函数
a = pd.Series([np.nan,2.5,0.0,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])

In [47]:
b = pd.Series([0.,np.nan,2.,np.nan,np.nan,5],index=['a','b','c','d','e','f'])

In [48]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [49]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [50]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [51]:
b.combine_first(a)

a    0.0
b    4.5
c    2.0
d    0.0
e    2.5
f    5.0
dtype: float64